travis:
  secure:
    BINSTAR_TOKEN: QqoQEHwDZLUeBWVUEzCVA0A5Oh820ofeqqbPp7EAObAPpMkMv1fAb/Vfhu7uPYg2YL89emyMZgfgv7+UQar7ecLKzYgaJdwuZkPeZz8E9kOHv4NCmwuwkGDjyIuV6eBWf1AX6ds/Lzmgx7ABC9y3wvqiLgDRUHUGBmNxivicfe8bSOsh9v9fe7BFszbk86sPmkLE5zhjuZSCn3kK8MyQAJWbGxm8hT4TNYr9Zxr8vgmlq0MiYJ1oscs6WNwpFcYsg240xOhQcU1U65MQoJTPOduEGxkU4LY8dC7dfBA0mJ8XBLw5t4e5cwDUorpw0dLtUrRnzh8DFUbNOxOyIxIll0qDRn174D0YR0vg1Zb0qPrEFzh3f08B7dtTAU7pRRpphVw0viHRZiiit07L2e92T7XnZalqkl2Jh3xOm8sRA5zhUrO2MDDj79XJ7A24O6+wR4Gq1l1lz2eFar/wZYA4q0Nl+R7PM+vZwcRwsNcGkJAaZ7XbMQ3Q6tuowId1ik59e8aHLHRYKT/HGwEE1ZVvQsOMl5N5RiBUbw18qlDwdp0aEQvgeD0bIemo4FXTnBaIt52dS1F84KAdSXn55t9KR7c4k553nP95TYkEfSBlV3QDgaulk0s2on8AtxKEezrAXDoJvpyxNh37EmG77pdJlengJSwFUbmCDwcz//aIj54=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
